apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80    