apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system           # the one created by bootstrap
  - namespaces            # our new folder
  - dotnet-app            # our HelmRelease folder
