replicaCount: 2

image:
  repository: dotnet-app-demo
  tag: "v1"
  pullPolicy: Never     # Important! We use local image only

service:
  type: ClusterIP
  port: 8080

release:
  namespace: dotnet-app   # optional but nice for slides / clarity  
