apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dotnet-app
  namespace: dotnet-app
spec:
  interval: 1m
  path: ./clusters/minikube/dotnet-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: dotnet-app
